name: Run clang-format linter

on:
  push:
  pull_request:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - uses: "DoozyX/clang-format-lint-action@latest"
      with:
        source: '.'
        extensions: 'h,cpp,c'
        exclude: './external'
        clangFormatVersion: 12
        style: 'file'
