name: Release setup

on:
  push:
    branches:
      - master

jobs:
  release-setup:
    runs-on: ubuntu-latest
    steps:
    - uses: "marvinpinto/action-automatic-releases@latest"  
      with:
        repo_token: "${{ secrets.GITHUB_TOKEN }}"
        automatic_release_tag: "continuous"
        prerelease: true
        title: "Continuous release"
