name: Ripes Tests

on:
  push:
    branches:
      - master
  pull_request:

jobs:
  build:
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
        os: [ubuntu-latest, macos-latest, ubuntu-16.04, ubuntu-18.04]

    steps:
    - uses: actions/checkout@v2
      with:
        submodules: recursive
    
    # Container preparation
    - if: contains( matrix.os, 'ubuntu')
      name: Prepare ubuntu container for build
      run: |
        sudo apt-get update
        sudo apt-get upgrade -y
        DEBIAN_FRONTEND=noninteractive sudo apt-get install -y -q --force-yes \
        automake cmake git wget libfuse2 desktop-file-utils tree \
        build-essential libgl1-mesa-dev libxkbcommon-x11-0 libpulse-dev
        echo "CC=gcc-9" >> $GITHUB_ENV
        echo "CXX=g++-9" >> $GITHUB_ENV


    - if: contains( matrix.os, 'macos')
      name: Prepare macos container for build
      run: brew install autoconf automake libtool xz  pkg-config libgit2 libjpg libpng libmtp


    # Qt installation
    - name: install Qt
      uses: jurplel/install-qt-action@v2
      with:
        version: '5.15.2'
        modules: 'qtcharts qtsvg'
        install-deps: false


    # Build ripes
    - name: build Ripes
      run: |
        cmake -DCMAKE_BUILD_TYPE=Release .
        make -j $(nproc)
