name: Windows / Qt 5.15
on:
  workflow_run:
    workflows: ["Release setup"]
    types: [completed]

jobs:
  buildWindows:
    runs-on: windows-latest

    steps:
    - name: get container ready for build
      uses: ilammy/msvc-dev-cmd@v1
    - uses: seanmiddleditch/gha-setup-ninja@master

    - name: Cache Qt
      id: cache-qt
      uses: actions/cache@v1
      with:
        path: ../Qt
        key: ${{ runner.os }}-QtCache-${{ matrix.qt-version }}

    - name: install Qt
      uses: jurplel/install-qt-action@v2
      with:
        version: '5.15.2'
        modules: 'qtcharts qtsvg'
        install-deps: false
        arch: win64_msvc2019_64
        cached: ${{ steps.cache-qt.outputs.cache-hit }}

    - name: checkout sources
      uses: actions/checkout@v2
      with:
        submodules: recursive

    - name: build Ripes
      shell: bash
      run: |
        cmake -GNinja -DCMAKE_BUILD_TYPE=Release -DCMAKE_C_COMPILER=cl -DCMAKE_CXX_COMPILER=cl
        cmake --build .

    - name: package artifacts
      shell: bash
      run: |
        source .github/scripts/set_version.sh
        APPNAME=Ripes-${RIPES_VERSION}-win-x86_64.zip
        echo "APPNAME=${APPNAME}" >> $GITHUB_ENV
        mkdir packageDir
        pushd packageDir
        mv ../Ripes.exe .
        windeployqt.exe -svg --release --no-compiler-runtime --no-opengl-sw --no-translations Ripes.exe
        7z a -r ../${APPNAME} *

    - name: continuous release
      uses: softprops/action-gh-release@v1
      with:
        files: ${{ env.APPNAME }}
        tag_name: continuous
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

    - name: tagged release
      uses: softprops/action-gh-release@v1
      if: startsWith(github.ref, 'refs/tags/')
      with:
        files: ${{ env.APPNAME }}
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
